# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5089dce7640679f01080b2f5eac399407b2b446f73d67b065da272c7ef07f0f2f8e91c3e398eca0dde83f823e66b3e975d26f0fe0caf1504e461cb1cce038c19

test:
  secret_key_base: c28b590bb2f949e00e628b4cd16332adaa01c2d651b1c0b56abe841c5b1c7232a203b8bdb5fadc0a15cd33d3791299f60752dfc62fa6f23448880a87ad136a1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
